Agrim/DAPI-614-615/edit app UI issues
deriv-com/deriv-api-docs pull request #106
Opened 2024-08-26 13:05 UTC by agrim-deriv

Styling and content fixes on edit application page.

2024-08-27 02:17 UTC, sandeep-deriv requested changes

2024-08-27 02:17 UTC, sandeep-deriv commented on src/components/CustomCheckbox/custom_checkbox.module.scss
> +  gap: 2rem;
@agrim-deriv let's keep it consistent with other values, make it `rem(2)` as above padding-top property

2024-08-27 02:17 UTC, sandeep-deriv commented on src/components/CustomCheckbox/custom_checkbox.module.scss
> +    bottom: 0.9375rem;
same here

2024-08-27 06:39 UTC, sandeep-deriv approved these changes

2024-08-29 06:08 UTC, ahmed-deriv approved these changes

2024-09-11 12:12 UTC, agrim-deriv commented
Closing this PR as a new PR has been generated from the new feature branch.

2024-09-11 12:12 UTC, closed without merging