Agrim/DAPI-629/ui fix popup
deriv-com/deriv-api-docs pull request #111
Opened 2024-09-02 10:31 UTC by agrim-deriv

Adjusting ui fixes on the popup

2024-09-05 02:46 UTC, ahmed-deriv requested changes

2024-09-05 02:46 UTC, ahmed-deriv commented on src/features/dashboard/components/Modals/AppRegisterSuccessModal/index.tsx
> +        <Text>
This `Text` tag seems like a container which should not be. Please try to use div or alternative if needed.

2024-09-05 02:46 UTC, ahmed-deriv commented on src/features/dashboard/components/Modals/AppRegisterSuccessModal/index.tsx
>        <div className='modal__icon' style={{ background: 'var(--core-color-solid-green-100)' }}>
Can we remove inline-css from here ?

2024-09-11 12:12 UTC, agrim-deriv commented
Closing this PR as a new PR has been generated from the new feature branch.

2024-09-11 12:12 UTC, closed without merging