fix: ios issue, ui fix, Ok button
deriv-com/deriv-api-docs pull request #126
Opened 2024-09-16 08:07 UTC by agrim-deriv

2024-09-17 11:52 UTC, prince-deriv approved these changes

2024-09-19 03:32 UTC, ahmed-deriv requested changes

2024-09-19 03:32 UTC, ahmed-deriv commented on src/features/dashboard/components/ApiTokenCard/index.tsx
> +    <div className={clsx(styles.api_token_card)} {...rest}>
can't we write just `className={styles.api_token_card}` ?

2024-09-19 03:32 UTC, ahmed-deriv commented on src/features/dashboard/components/ApiTokenCard/index.tsx
> +  const handleAdminScopeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
can we refactor this function as I see lot of redundancy of setState's in `handleAdminScopeChange, handleModalPrimaryButton and handleModalSecondaryButton` ?

2024-09-26 05:50 UTC, ahmed-deriv approved these changes

2024-09-26 06:03 UTC, ahmed-deriv commented on src/features/dashboard/components/ApiTokenTable/index.tsx
> +      {loading ? (
We need to refactor this one. Its not correct.

2024-09-26 06:35 UTC, merged