fix: removing extra divs, fixing styling on 2 tabs, everything in quill
deriv-com/deriv-api-docs pull request #127
Opened 2024-09-19 12:16 UTC by agrim-deriv

2024-09-20 03:14 UTC, ahmed-deriv requested changes
There are few code files that belongs to different PR once its approved and merge. Will review again.

2024-09-20 03:14 UTC, ahmed-deriv commented on src/components/CustomCheckbox/index.tsx
Is it only UI changes or logics changes as well ?

2024-09-20 03:14 UTC, ahmed-deriv commented on src/features/dashboard/components/ApiTokenCard/index.tsx
Same as here.

2024-09-20 03:14 UTC, ahmed-deriv commented on src/features/dashboard/update-app/AppUpdateForm/app-update-form.scss
>    .mblk {
can you create root values and also create this style into global file to reuse this spacing on other pages/components if needed. Also use `rem` to all places as some have value in pixels and some have `rem`

2024-09-20 08:32 UTC, agrim-deriv commented on src/components/CustomCheckbox/index.tsx
Mostly UI

2024-09-26 07:10 UTC, prince-deriv approved these changes

2024-09-26 07:30 UTC, merged