Agrim/filtering
deriv-com/deriv-api-docs pull request #92
Opened 2024-08-13 05:39 UTC by agrim-deriv

2024-08-14 02:39 UTC, ahmed-deriv requested changes

2024-08-14 02:39 UTC, ahmed-deriv commented on src/features/Apiexplorer/Dropdown/DropdownList/index.tsx
>  const filterOptions = (options, query) => {
type missing here

2024-08-14 02:39 UTC, ahmed-deriv commented on src/features/Apiexplorer/Dropdown/DropdownList/index.tsx
> +    const lowerCaseTitle = option.title.toLowerCase();
I think variable name should be `title` we dont need to write lowerCase with it.

2024-08-14 04:59 UTC, ahmed-deriv approved these changes

2024-08-26 05:43 UTC, shafin-deriv approved these changes

2024-08-26 07:38 UTC, merged